In [26]:
import pandas as pd
df = pd.read_csv('../data/train_apps_rfcd_seo_mod.csv', parse_dates=True)

In [27]:
cat_columns = ['sponsor', 'grant_category', 'sponsor_c', 'grant_category_c']
for cat_column in cat_columns :
    df[cat_column] = df[cat_column].astype('category')
    df[cat_column] = df[cat_column].cat.codes

In [28]:
from datetime import date
hard_date = date(2005, 1, 1)

In [30]:
df

,id,granted,sponsor,grant_category,grant_value,date,sponsor_c,sponsor_n,grant_category_c,grant_category_n,...,SEO_72,SEO_73,SEO_74,SEO_75,SEO_76,SEO_77,SEO_78,SEO_99,RFCD_OTHER,SEO_OTHER
0,1,1,172,0,5000,8/11/05,0,29,0,10,...,0,0,0,0,0,0,0,0,100,100
1,2,1,173,0,10000,11/11/05,1,2,0,10,...,0,0,0,0,0,0,0,0,0,0
2,3,1,172,1,5000,14/11/05,0,29,1,10,...,0,0,0,0,0,0,0,0,0,0
3,4,1,188,1,20000,15/11/05,3,40,1,10,...,0,100,0,0,0,0,0,0,0,0
4,5,0,211,0,5000,16/11/05,2,59,0,10,...,0,100,0,0,0,0,0,0,0,0
5,6,1,204,0,40000,19/11/05,3,4,0,10,...,0,0,0,0,0,100,0,0,0,0
6,7,0,173,0,10000,19/11/05,1,2,0,10,...,0,100,0,0,0,0,0,0,0,0
7,8,0,165,5,5000,19/11/05,3,28,1,30,...,0,0,0,0,0,100,0,0,0,0
8,9,1,173,0,200000,19/11/05,1,2,0,10,...,0,100,0,0,0,0,0,0,0,0
9,10,1,173,0,5000,19/11/05,1,2,0,10,...,0,0,0,0,0,0,100,0,0,0
10,11,1,173,0,100000,19/11/05,1,2,0,10,...,0,0,0,0,0,100,0,0,0,0
11,12,0,18,5,5000,19/11/05,3,136,1,30,...,0,0,100,0,0,0,0,0,0,0
12,13,1,204,0,10000,19/11/05,3,4,0,10,...,0,100,0,0,0,0,0,0,0,0
13,14,0,173,1,5000,19/11/05,1,2,1,10,...,0,100,0,0,0,0,0,0,0,0
14,15,1,173,0,5000,19/11/05,1,2,0,10,...,0,100,0,0,0,0,0,0,0,0
15,16,0,0,1,10000,19/11/05,3,100,1,10,...,0,0,0,0,0,0,0,0,0,0
16,17,0,86,0,10000,19/11/05,0,1,0,10,...,0,100,0,0,0,0,0,0,0,0
17,18,1,107,12,5000,19/11/05,0,21,0,50,...,0,100,0,0,0,0,0,0,0,0
18,19,1,173,0,50000,19/11/05,1,2,0,10,...,0,0,34,33,0,33,0,0,0,0
19,20,0,135,5,5000,19/11/05,3,24,1,30,...,0,0,0,0,0,0,100,0,0,0
20,21,1,31,5,5000,19/11/05,3,148,1,30,...,0,100,0,0,0,0,0,0,0,0
21,22,0,12,5,5000,19/11/05,3,12,1,30,...,0,100,0,0,0,0,0,0,0,0
22,23,0,214,1,5000,19/11/05,1,62,1,10,...,0,0,0,100,0,0,0,0,0,0
23,24,1,173,0,30000,19/11/05,1,2,0,10,...,0,100,0,0,0,0,0,0,0,0
24,25,1,20,5,5000,19/11/05,1,138,1,30,...,0,0,0,0,0,0,0,0,0,0
25,26,0,213,11,5000,19/11/05,3,60,2,40,...,0,0,100,0,0,0,0,0,0,0
26,27,0,173,12,20000,19/11/05,1,2,0,50,...,0,0,0,0,0,0,0,0,100,100
27,28,0,30,0,10000,19/11/05,2,147,0,10,...,0,0,0,0,0,0,0,0,100,100
28,29,0,213,7,5000,19/11/05,3,60,3,30,...,0,80,0,0,0,0,20,0,0,0
29,30,1,173,0,10000,19/11/05,1,2,0,10,...,0,100,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6603,6604,1,92,5,5000,10/12/07,0,205,1,30,...,0,100,0,0,0,0,0,0,0,0
6604,6605,0,10,0,10000,11/12/07,1,126,0,10,...,0,100,0,0,0,0,0,0,0,0
6605,6606,1,196,0,5000,11/12/07,3,432,0,10,...,0,0,0,0,0,60,0,0,0,0
6606,6607,1,155,10,100000,12/12/07,2,279,6,30,...,0,0,0,0,0,100,0,0,0,0
6607,6608,1,107,12,5000,12/12/07,0,21,0,50,...,0,100,0,0,0,0,0,0,10,0
6608,6609,1,201,1,5000,13/12/07,2,47,1,10,...,0,0,0,100,0,0,0,0,0,0
6609,6610,1,182,0,5000,13/12/07,3,36,0,10,...,0,90,0,0,0,0,10,0,0,0
6610,6611,1,155,10,100000,13/12/07,2,279,6,30,...,0,100,0,0,0,0,0,0,0,0
6611,6612,1,204,3,5000,14/12/07,3,4,2,20,...,0,100,0,0,0,0,0,0,0,0
6612,6613,1,17,10,5000,14/12/07,2,135,6,30,...,0,100,0,0,0,0,0,0,0,0
6613,6614,0,228,0,40000,14/12/07,2,7,0,10,...,0,0,0,0,0,0,100,0,0,0
6614,6615,1,204,0,10000,14/12/07,3,4,0,10,...,0,0,0,0,0,0,0,0,0,0
6615,6616,0,228,0,5000,14/12/07,2,7,0,10,...,0,0,0,0,0,0,0,0,100,100
6616,6617,0,228,0,5000,17/12/07,2,7,0,10,...,0,0,0,0,0,0,0,0,0,0
6617,6618,0,228,0,5000,17/12/07,2,7,0,10,...,0,0,0,0,0,0,0,0,100,100
6618,6619,1,230,5,5000,17/12/07,0,81,1,30,...,0,0,0,0,0,0,0,0,100,100
6619,6620,0,228,0,10000,17/12/07,2,7,0,10,...,0,100,0,0,0,0,0,0,0,0
6620,6621,0,228,0,5000,17/12/07,2,7,0,10,...,0,0,0,0,0,0,0,0,100,100
6621,6622,0,214,5,20000,18/12/07,1,62,1,30,...,0,0,0,0,0,0,0,0,100,100
6622,6623,1,107,5,5000,18/12/07,0,21,1,30,...,0,0,0,0,0,0,0,0,100,100
6623,6624,0,228,0,5000,18/12/07,2,7,0,10,...,0,0,0,0,0,0,0,0,100,100
6624,6625,0,214,5,20000,18/12/07,1,62,1,30,...,0,0,0,0,0,0,0,0,100,100
6625,6626,1,223,5,5000,18/12/07,0,73,1,30,...,0,0,0,0,0,0,0,0,100,100
6626,6627,1,181,6,10000,19/12/07,1,34,2,30,...,0,0,0,0,0,100,0,0,0,0
6627,6628,1,181,6,5000,19/12/07,1,34,2,30,...,0,0,0,0,0,0,0,0,100,100
6628,6629,1,212,5,5000,19/12/07,0,5,1,30,...,0,100,0,0,0,0,0,0,0,0
6629,6630,1,107,5,10000,20/12/07,0,21,1,30,...,0,100,0,0,0,0,0,0,0,0
6630,6631,1,111,3,30000,20/12/07,2,223,2,20,...,0,0,0,0,0,0,0,0,0,0
6631,6632,1,204,0,40000,21/12/07,3,4,0,10,...,0,0,0,0,0,0,30,0,0,0
6632,6633,1,212,5,5000,21/12/07,0,5,1,30,...,0,0,0,0,0,0,0,0,100,100

In [24]:
df['date']-hard_date

TypeError: unsupported operand type(s) for -: 'str' and 'datetime.date'